### PR TITLE
Add more math things from std.math

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Vexu** [comment]
Thanks!

**Comment by data-man** [comment]
What about:
```zig
ftruemin = math.f64_true_min
fmin = math.f64_min
fmax = math.f64_max
fepsilon = math.f64_epsilon
ftoint = math.f64_toint
nan = math.nan_f64
inf = math.inf_f64
imin = ...
imax = ...
etc.
```
Thoughts?

**Comment by data-man** [comment]
Ooops, I'm too slow. :rofl:

**Comment by Vexu** [comment]
Most of those would be good to have, though I'd drop the f prefix since I'm calling them numbers not floats.

**Pull request merged**
